version: 0.2

env: 
  variables: 
    GIT_HOST: github.com

phases:
  pre_build:
    commands:
      - mkdir -p ~/.ssh                   # Ensure the .ssh directory exists
      - echo "$SSH_KEY" > ~/.ssh/ssh_key  # Save the machine user's private key
      - chmod 600 ~/.ssh/ssh_key          # Adjust the private key permissions (avoids a critical error)
      - eval "$(ssh-agent -s)"            # Initialize the ssh agent
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - mkdir root && cd root
      # SSH Credentials have been set up. Check for a .git directory to determine if we need to set up our git package
      - |
        if [ ! -d ".git" ]; then
          git init                                                                          # Initialize Git
          git remote add origin git@github.com:klu1211/dvc-poc.git                          # Add the remote origin so we can fetch
          git fetch                                                                         # Get all the things
          git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"                              # Checkout the specific commit we are building
        fi
      - apt update -y
      - apt upgrade -y
      - pip install dvc
      - pip install boto3
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
      - dvc pull Dvcfile
  build:
    commands:
      - docker build --tag 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$(git describe --tag)
  post_build:
    commands:
      - docker container run 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$(git describe --tag) code/read_concatenate_files.py --config_file_path code/config.yml
      - docker push 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$(git describe --tag)
