version: 0.2

phases:
  pre_build:
    commands:
      - sudo apt update
      - sudo apt install python3-pip
      - pip3 install dvc
      - pip3 install boto3
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
      - docker build --tag 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$(git describe --tag) 
  post_build:
    commands:
      - docker push 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$(git describe --tag)

