version: 0.2

phases:
  pre_build:
    commands:
      - git log
      - apt update -y
      - apt upgrade -y
      - pip install dvc
      - pip install boto3
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
      - dvc pull Dvcfile
  build:
    commands:
      - docker build --tag 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$CODEBUILD_GIT_TAG
  post_build:
    commands:
      - docker container run 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$CODEBUILD_GIT_TAG code/read_concatenate_files.py --config_file_path code/config.yml
      - docker push 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$CODEBUILD_GIT_TAG
