version: 0.2

phases:
  pre_build:
    commands:
      - sudo apt-get update
      - sudo apt-get upgrade
      - sudo apt-get install python3.6 -y
      - pip3 install dvc
      - pip3 install boto3
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
      - dvc pull Dvcfile
  build:
    commands:
      - docker build --tag 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$(git describe --tag) 
  post_build:
    commands:
      - docker container run 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$(git describe --tag) code/read_concatenate_files.py --config_file_path code/config.yml
      - docker push 889433419955.dkr.ecr.ap-southeast-2.amazonaws.com/dvc-poc:$(git describe --tag)

